name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia banco
      run: docker compose up -d postgres

    - name: Lint
      uses: golangci/golangci-lint-actions@v6
      with: 
        version: v1.59

    - name: Test
      run: go test -v main_test.go